site_name: IT - Lerndokumentation
site_description: Dokumentation zu IT-Themen, Netzwerken, Sicherheit, Linux und Tools
site_url: https://sitename.example.com

extra_css:
  - assets/css/custom.css

nav:
  - Home: index.md
  - Network: 
    - Network/index.md
  - Security: 
    - Security/index.md
  - Linux: 
    - Linux/index.md
  - Pogrammieren:
    - Programmieren/index.md
  - Fachinformatiker: 
    - Fachinformatiker/index.md
  - Tools: 
    - Tools/index.md
    - Git: Tools/Git/index.md
    - MkDocs: Tools/MkDocs/index.md
    


plugins:
  - search:
      enabled: true
      lang: de
  - glightbox:
      enabled: true
      lightbox: true # Lightbox f체r Bilder

theme: 
  language: de
  name: material
  font:
  #  text:  Merriweather Sans
    code: Red Hat Mono
  logo: assets/vogel.png
  # favicon: assets/favicon.ico
  palette:
    
    # Palette toggle for light mode
    - scheme: daura
      primary: amber
      accent: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode


    # scheme: aura
    # primary: amber
    # accent: deep orange
    
    # scheme: default    # Light mode
    # scheme: slate      # Dark mode
    # scheme: aura       # Warmes Orange/Pink 
    # scheme: espresso   # Kaffee-채hnlich (hellbraun)
    # scheme: aqua       # Frisches T체rkis
    # scheme: feather    # Sehr helles Grau/Blau
    
  features:
    - navigation.footer
    - navigation.path    # Breadcrumbs nur f체r Sponsoren :(
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.indexes
    - navigation.sections
    - navigation.expand
  

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details

# extra:
#  social:
#    - icon: simple/youtube
#      link: https://youtube.com/@marco-schwuchow
#    - icon: simple/linkedin
#      link: https://linkedin.com/in/marco-schwuchow

copyright: Copyright &copy; 2025 Marco Schwuchow